version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/daily_notes
    restart: unless-stopped
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
