services:
  backend:
    container_name: flask-backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - mongo
    networks:
      - daily-network

  frontend:
    container_name: nuxt-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - daily-network

  mongo:
    image: mongo:4.4
    container_name: mongo-daily
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - daily-network

volumes:
  mongo-data:

networks:
  daily-network:
    driver: bridge