services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - daily-network

  frontend:
    build:
      context: ./frontend
    container_name: nuxt-frontend
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - daily-network

networks:
  daily-network:
    driver: bridge